# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 270d4943ff251c7eaeb340a149d92da6b4d8baa562cbdfd5100eca871dd38fba1d4af16a74486c3f031dc29c8aa7d0d515d056e9401f5e550aeb19b6787a9582

test:
  secret_key_base: 5480604309b6eebb941999012ff1cdf9f4aecf06e9d339a1ff4a5d9bd851835f183eb96f624dd76205eaa3e44b0d68dcb6bbe1980f6de0d8667e4554e4ebacbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
